In [112]:
import pandas as pd

In [113]:
import numpy as np

In [114]:
mydata=pd.read_csv(r"C:\Users\Rads Gupta\Downloads\DataSets-master\DataSets-master\Housing_Data.csv")

In [115]:
mydata

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,1,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,2,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,3,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,4,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,5,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
5,6,66000.0,4160,3,1,1,yes,yes,yes,no,yes,0,no
6,7,66000.0,3880,3,2,2,yes,no,yes,no,no,2,no
7,8,69000.0,4160,3,1,3,yes,no,no,no,no,0,no
8,9,83800.0,4800,3,1,1,yes,yes,yes,no,no,0,no
9,10,88500.0,5500,3,2,4,yes,yes,no,no,yes,1,no
10,11,90000.0,7200,3,2,1,yes,no,yes,no,yes,3,no
11,12,30500.0,3000,2,1,1,no,no,no,no,no,0,no
12,13,27000.0,1700,3,1,2,yes,no,no,no,no,0,no
13,14,36000.0,2880,3,1,1,no,no,no,no,no,0,no
14,15,37000.0,3600,2,1,1,yes,no,no,no,no,0,no
15,16,37900.0,3185,2,1,1,yes,no,no,no,yes,0,no
16,17,40500.0,3300,3,1,2,no,no,no,no,no,1,no
17,18,40750.0,5200,4,1,3,yes,no,no,no,no,0,no
18,19,45000.0,3450,1,1,1,yes,no,no,no,no,0,no
19,20,45000.0,3986,2,2,1,no,yes,yes,no,no,1,no
20,21,48500.0,4785,3,1,2,yes,yes,yes,no,yes,1,no
21,22,65900.0,4510,4,2,2,yes,no,yes,no,no,0,no
22,23,37900.0,4000,3,1,2,yes,no,no,no,yes,0,no
23,24,38000.0,3934,2,1,1,yes,no,no,no,no,0,no
24,25,42000.0,4960,2,1,1,yes,no,no,no,no,0,no
25,26,42300.0,3000,2,1,2,yes,no,no,no,no,0,no
26,27,43500.0,3800,2,1,1,yes,no,no,no,no,0,no
27,28,44000.0,4960,2,1,1,yes,no,yes,no,yes,0,no
28,29,44500.0,3000,3,1,1,no,no,no,no,yes,0,no
29,30,44900.0,4500,3,1,2,yes,no,no,no,yes,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,517,95000.0,6000,3,2,3,yes,yes,no,no,yes,0,no
517,518,96500.0,6000,4,2,4,yes,no,no,no,yes,0,no
518,519,101000.0,6240,4,2,2,yes,no,no,no,yes,1,no
519,520,102000.0,6000,3,2,2,yes,yes,no,no,no,1,no
520,521,103000.0,7680,4,2,4,yes,yes,no,no,yes,1,no
521,522,105000.0,6000,4,2,4,yes,yes,no,no,yes,1,no
522,523,108000.0,6000,4,2,4,yes,no,no,no,yes,1,no
523,524,110000.0,6000,4,2,4,yes,no,no,no,no,2,no
524,525,113000.0,6000,4,2,4,yes,no,no,no,yes,1,no
525,526,120000.0,7475,3,2,4,yes,no,no,no,yes,2,no
526,527,105000.0,5150,3,2,4,yes,no,no,no,yes,2,no
527,528,106000.0,6325,3,1,4,yes,no,no,no,yes,1,no
528,529,107500.0,6000,3,2,4,yes,no,no,no,yes,1,no
529,530,108000.0,6000,3,2,3,yes,no,no,no,yes,0,no
530,531,113750.0,6000,3,1,4,yes,yes,no,no,yes,2,no
531,532,120000.0,7000,3,1,4,yes,no,no,no,yes,2,no
532,533,70000.0,12900,3,1,1,yes,no,no,no,no,2,no
533,534,71000.0,7686,3,1,1,yes,yes,yes,yes,no,0,no
534,535,82000.0,5000,3,1,3,yes,no,no,no,yes,0,no
535,536,82000.0,5800,3,2,4,yes,no,no,no,yes,0,no
536,537,82500.0,6000,3,2,4,yes,no,no,no,yes,0,no
537,538,83000.0,4800,3,1,3,yes,no,no,no,yes,0,no
538,539,84000.0,6500,3,2,3,yes,no,no,no,yes,0,no
539,540,85000.0,7320,4,2,2,yes,no,no,no,no,0,no
540,541,85000.0,6525,3,2,4,yes,no,no,no,no,1,no
541,542,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,543,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,544,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,545,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,546,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [116]:
mydata.keys()

Index(['Unnamed: 0', 'price', 'lotsize', 'bedrooms', 'bathrms', 'stories',
       'driveway', 'recroom', 'fullbase', 'gashw', 'airco', 'garagepl',
       'prefarea'],
      dtype='object')

In [117]:
mydata.head()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,1,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,2,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,3,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,4,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,5,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [118]:
i=mydata["lotsize"].values

In [119]:
i.shape

(546,)

In [120]:
t=mydata["price"].values

In [121]:
t.shape

(546,)

In [122]:
#data processing

In [123]:
type(i)

numpy.ndarray

In [124]:
i.shape

(546,)

In [127]:
inp=i.reshape(len(i),1)

In [128]:
t.shape

(546,)

In [129]:
from sklearn.model_selection import train_test_split

In [130]:
xtrain,xtest,ytrain,ytest=train_test_split(i,t,test_size=0.2)

In [131]:
xtrain.shape

(436,)

In [132]:
ytrain.shape

(436,)

In [133]:
xtest.shape

(110,)

In [134]:
ytest.shape

(110,)

In [135]:
xtrain

array([ 4000,  6900,  4500,  6000,  3630,  3450,  7160,  4040, 16200,
        2970,  3640,  9960,  2610,  6350,  7200,  4500,  5500,  5900,
        9000,  6600,  9000,  3040,  4320,  7600,  2850,  4700,  6040,
        4350,  4500,  3520,  4320,  4815,  7000,  5800,  5750,  3000,
        6000,  6000,  7155,  6000,  4800,  3640,  3090,  3000,  3090,
        4000,  4032, 10269,  4095,  4920,  4000,  2145,  5400,  7475,
        3500,  4800,  1905,  6060,  5320,  3640,  2800,  4960,  5450,
        3640,  4400,  3000,  3520,  3792,  6300,  5200,  3760,  5076,
        4600,  3630,  6710,  5640,  6000,  8250,  4632,  5200,  1650,
        3520,  2145,  8372,  3210,  7420,  4820,  3600,  6420,  3180,
        4785,  2145,  4095,  4352,  3450,  2175,  2520,  4340,  3640,
        6600,  6325,  9166,  6500,  9000,  8250,  3620,  9000,  4600,
        4500,  5400,  2176,  4360,  8050,  5800,  2430,  5150,  3264,
        3000,  3000, 12090,  6540,  2787,  8520,  3000, 11460,  3600,
        2650,  8250,  5500,  2500,  4046,  6440,  6360,  1950,  1836,
        5600,  6000,  4775,  6000,  6480,  8400,  4100,  6600,  4500,
        2398,  4400,  4120,  8875,  6000,  6615,  6615,  4000,  6650,
        3540,  4050,  5500,  2880,  3650,  8580,  7680,  6800,  2910,
        8100,  3480,  5830,  3000,  8100,  7700,  2000,  6000,  5500,
        5300, 10500,  8800,  8960,  4500,  3000,  3150,  4160,  3500,
        4600,  4770,  2400,  3600,  8250,  5850,  3120,  6800,  3970,
        4000,  3069,  5880,  3635,  6000,  5500,  6600,  4520,  6540,
        3570,  3000,  3970,  3036,  2880,  3800,  3150,  3000, 12900,
        6360,  5885,  5000,  5500,  5960,  3850,  3850,  4040,  2640,
        6930,  3060,  4000,  6000,  3450,  3960,  4600, 10240,  3986,
        3800,  3500,  6840, 10500,  9500,  8400,  6550,  5400,  6000,
        5010,  3410,  4000,  5320,  3420,  6100,  4500,  4075,  6000,
        6600,  3968,  3850,  3780,  5500,  3700,  3600,  3300,  6420,
        2275,  2160,  5680,  6100,  5136,  8050,  5170,  4500,  7000,
        3520,  3600,  6450,  3480,  4500,  4992,  4040,  6000,  8150,
        5020,  4120,  4990,  3630,  2145,  3400, 10700,  7152,  2325,
        2835,  6000,  8500,  6240,  6525,  5000,  3630,  2135,  6360,
        2700,  3185,  5828,  4260,  4500,  4320, 10360,  3450,  4800,
        6000,  3162,  6540,  4500,  7700,  5850,  5400,  3180,  7980,
        4800,  6500,  4130,  6321,  4510,  3649,  4400,  6360,  3240,
        3150, 10500,  7000,  4880,  4000,  7200,  4200,  5300,  3760,
        6420,  7482,  7770, 11175,  6210,  4260,  2400,  3640,  5960,
        6600,  4500,  2856,  3180,  5495,  3990,  4880,  7420,  3460,
        3930,  2550,  6660,  7020,  8580,  3185,  4050,  3000,  6825,
        6400, 13200,  7440,  3180,  3450,  3900,  6720,  4560,  9800,
        5948,  4750,  4510,  3520,  3120,  5985,  4160,  4995, 13200,
        4100,  3460,  6600,  2800,  7686,  3180,  3840,  7800,  3630,
        5000,  3630,  7440,  7410,  4410,  5450,  3290,  3880,  3512,
        4300,  3500,  9860,  3150,  6000,  6254,  2990,  3584,  3180,
        8880,  6000,  3480,  7500,  4960,  4600,  3750,  7950,  9620,
        3680,  4300,  7000,  2953,  3510,  4500, 11440,  6480,  2910,
        2015,  3360,  3720,  1950,  5700,  4350, 11410,  3300,  4410,
        3816,  5400,  3350,  2700,  2684,  3750,  2610,  6100,  4950,
        3480,  5400,  4646,  3120], dtype=int64)

In [136]:
ytrain

array([  65500.,   86000.,   46500.,   82500.,   52500.,   48500.,
         84000.,   47500.,  145000.,   70000.,   65000.,  175000.,
         49000.,   88500.,   90000.,   44900.,   75000.,   58000.,
         90000.,  107000.,   45000.,   41000.,   67000.,   72000.,
         52000.,   80000.,   69000.,   40500.,   51000.,   64500.,
         46000.,   69000.,   82900.,   70000.,  140000.,   58000.,
         98000.,   90000.,  124000.,  107500.,   71900.,   51000.,
         44000.,   30500.,   43000.,   94500.,   61700.,   75000.,
         45000.,   62900.,   97000.,   49500.,   79500.,  120000.,
         62000.,   80000.,   62000.,   47000.,   49500.,   48500.,
         38000.,   48000.,   88000.,   50000.,   37000.,   30000.,
         60000.,   47000.,   70000.,   83000.,   65000.,   43000.,
        127000.,   52500.,   77000.,   52500.,   89500.,   93000.,
         59000.,   40750.,   45000.,   51900.,   47000.,   87000.,
         35000.,  190000.,   54000.,   50000.,   85000.,   47000.,
         48500.,   60000.,   70000.,   42500.,   45000.,   61000.,
         53900.,   58000.,   46200.,   89000.,  106000.,   68000.,
         95000.,  103500.,   64000.,   25000.,  114000.,   75500.,
         51000.,   57500.,   55000.,   61000.,  123500.,   82000.,
         38000.,  105000.,   34000.,   56000.,   44500.,   97000.,
         75000.,   60500.,   75000.,   70000.,   83900.,   52500.,
         40000.,   53900.,  120000.,   47000.,   59500.,   67900.,
        100500.,   32000.,   32500.,   58500.,   96500.,   47500.,
         41000.,  110000.,   75000.,   64900.,   87000.,   44000.,
         44555.,   79500.,   48000.,  120000.,  105000.,   42000.,
         87000.,   49000.,   60500.,   72000.,   57000.,   89000.,
         36000.,   50000.,  145000.,  103000.,   86000.,   37200.,
         44100.,   50000.,   54000.,   35500.,   68500.,   98500.,
         38000.,  108000.,   56000.,   75000.,   80000.,  122500.,
        175000.,   60000.,   73000.,   51000.,   69000.,   44500.,
         43000.,   70000.,   30000.,   37000.,   59900.,   60000.,
         52900.,   39000.,   32500.,   37900.,   45000.,   47000.,
         34400.,  120900.,   80000.,   89900.,   70000.,   85000.,
         52000.,   26000.,   32500.,   50000.,   62900.,   43500.,
         42000.,   36000.,   70000.,   61000.,   64000.,   82000.,
         88500.,  117000.,   25000.,   50500.,   64000.,   40500.,
         53900.,   49500.,   38000.,  103000.,   64500.,   92500.,
         50000.,   68000.,   45000.,   75000.,   45000.,  116000.,
         94500.,   50000.,   65000.,  133000.,   82000.,  108000.,
         66000.,   73500.,   39000.,   65000.,   69900.,   79000.,
         62000.,   62000.,  102000.,   95500.,   63000.,   55000.,
         55500.,   83900.,   85000.,   37000.,   79000.,   95000.,
         52000.,   44000.,   66000.,   78000.,   80000.,   42900.,
         67000.,   74500.,  115442.,   65000.,   42000.,   76900.,
         42000.,   88000.,   58000.,   95000.,   95000.,   71500.,
         96000.,   70000.,   64900.,   43000.,   47600.,   61100.,
         72000.,   55000.,   60000.,   43000.,   94700.,  128000.,
        101000.,   85000.,   82000.,   38000.,   50000.,   80000.,
         42000.,   48000.,   83000.,   95000.,   57000.,  125000.,
         61500.,   59900.,   83800.,  130000.,   63900.,  122000.,
         57250.,   35000.,   42000.,   41000.,   55500.,   78500.,
         91500.,   84000.,   52000.,   68000.,   64000.,   27000.,
         35500.,  112000.,   43000.,   54500.,   80000.,   68500.,
         62900.,   60000.,   74500.,   70100.,   55000.,   93000.,
         87500.,  114900.,   61000.,  100000.,   78000.,   75000.,
         25245.,   60000.,   52000.,   78000.,   51500.,   54000.,
         52000.,   44700.,   50000.,  118500.,  163000.,   57500.,
         46500.,   65000.,   80750.,   85000.,   92000.,   49000.,
         53000.,   35000.,   77500.,   90000.,   99000.,  106000.,
         74500.,   45000.,   62500.,   70000.,  123500.,   75000.,
         70500.,   48000.,   65900.,   52000.,   46000.,   59000.,
         66000.,   69900.,  140000.,   57000.,   57250.,  130000.,
         70800.,   71000.,   33000.,   65500.,   76000.,   41000.,
         92000.,   67000.,  106000.,   92500.,   60000.,   52900.,
         56000.,   66000.,   50000.,  106500.,   35000.,   64500.,
         78000.,  138300.,   85000.,   26500.,   53000.,   55000.,
         99000.,  110000.,   38000.,  155000.,   44000.,   60000.,
         48000.,  120000.,   86900.,   58500.,   86900.,  120000.,
         60000.,   64500.,   61000.,  104900.,   57000.,   25000.,
         55000.,   30000.,   48000.,   49000.,   95000.,   69500.,
         73000.,   40500.,   71000.,   56000.,   67000.,   54800.,
         47900.,   46000.,   43000.,   60000.,   73000.,   62600.,
         47000.,   70000.,   70000.,   50000.])